// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "musication-hosting",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d312rk7qk4a72n.cloudfront.net",
    "aws_cognito_identity_pool_id": "eu-west-1:fe339e6f-ba4d-49c4-a0af-2f4aa3828f41",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_tfme2LnVF",
    "aws_user_pools_web_client_id": "107dseo3ul0hrjqo2h9rp8ertk",
    "aws_user_files_s3_bucket": "musication-mp3s",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "mappings",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "musicationApi",
            "endpoint": "https://v6311atj7a.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
